services:
    php:
        build:
            context: ./docker/php
        container_name: laravel-php
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        environment:
            - DB_HOST=localhost  # Replace with your actual MySQL host
            - DB_PORT=3306
            - DB_DATABASE=kubernetes
            - DB_USERNAME=root
            - DB_PASSWORD=Manik@1234
            - REDIS_HOST=localhost  # Replace with your actual Redis host
            - REDIS_PORT=6379

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - php

    node:
        build:
            context: ./docker/nodejs  # Ensure this points to the directory containing the Dockerfile
        container_name: laravel-node
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        command: [ "npm", "run", "dev" ]

networks:
    laravel-network:
        driver: bridge
