services:
    php:
        build:
            context: ./docker/php  # Path to the directory containing the PHP Dockerfile
        container_name: laravel-php
        volumes:
            - .:/var/www  # Mount the entire project directory (including composer.json)
        networks:
            - laravel-network
        environment:
            - DB_HOST=localhost
            - DB_PORT=3306
            - DB_DATABASE=kubernetes
            - DB_USERNAME=root
            - DB_PASSWORD=Manik@1234
            - REDIS_HOST=localhost
            - REDIS_PORT=6379

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - php

    node:
        build:
            context: ./docker/nodejs
        container_name: laravel-node
        volumes:
            - .:/var/www  # Mount the entire project directory
        networks:
            - laravel-network
        command: ["npm", "run", "dev"]
        ports:
            - "3000:3000"  # Expose the dev server port

networks:
    laravel-network:
        driver: bridge
