services:
    laravel_app:
        platform: linux/amd64
        build:
            args:
                user: laravel_user
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel_app_image
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        environment:
            - DB_HOST=host.docker.internal      # MySQL running on the host
            - DB_PORT=3306                      # MySQL default port
            - DB_DATABASE=kubernetes            # Database name
            - DB_USERNAME=root                  # Database username
            - DB_PASSWORD=Manik@1234            # Database password
            - REDIS_HOST=host.docker.internal   # Redis running on the host
            - REDIS_PORT=6379                   # Redis default port
        volumes:
            - ./:/var/www
        networks:
            - laravel_network
        ports:
            - "8082:9000"

    laravel_webserver:
        platform: linux/amd64
        image: nginx:alpine
        container_name: laravel_webserver_container
        restart: unless-stopped
        ports:
            - "6162:80"
        depends_on:
            - laravel_app
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

