services:
    laravel_app:
        build:
            context: ./docker/laravel_app
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8082:9000"  # Map port 9000 inside the container to port 8082 on your host
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=kubernetes
            - DB_USERNAME=root
            - DB_PASSWORD=Manik@1234
            - REDIS_HOST=host.docker.internal
            - REDIS_PORT=6379
        networks:
            - laravel_network

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: nginx_container
        ports:
            - "6162:80"  # Expose Nginx on port 6162
        depends_on:
            - laravel_app
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel_network

    nodejs:
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        container_name: nodejs_container
        volumes:
            - .:/var/www
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
